INSERT INTO BLOOD_GROUPS VALUES(1, 'B+');
INSERT INTO BLOOD_GROUPS VALUES(2, 'B-');
INSERT INTO BLOOD_GROUPS VALUES(3, 'O+');

INSERT INTO DONARS VALUES(1, 23, 'Rk-1', 'Bk',sysdate, 1);
INSERT INTO DONARS VALUES(2, 23, 'Rk-2', 'Bk',sysdate, 3);
INSERT INTO DONARS VALUES(3, 23, 'Rk-3', 'Bk',sysdate, 2);
INSERT INTO DONARS VALUES(4, 23, 'Rk-4', 'Bk',sysdate, 1);